### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by shobhitJava** [TangoJ-Labs/fabric-production-tutorials#1]
Hi There

When I am firing the command to enroll the CA admin from cli. I am getting connection refused error. Please find the error below:

POST https://org1-ca:7054/enroll
{"hosts":["00e808471e05"],"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIIBSjCB8QIBADBlMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xp\nbmExFDASBgNVBAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMxFjAUBgNV\nBAMTDW9yZzEtYWRtaW4tY2EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASBr8+2\nnzdzj2MhJfTTgEsqt+p1AyKlXlrnq+Nd3MGX74mhpgeNEatlTfAxP5vCgMZ8o276\n1l9m8pD56NaXQqXeoCowKAYJKoZIhvcNAQkOMRswGTAXBgNVHREEEDAOggwwMGU4\nMDg0NzFlMDUwCgYIKoZIzj0EAwIDSAAwRQIhAIiWAai73sulrAcB4J1g/17VxekV\naW3/tCKQqCTiaYtEAiAoxUcleJ99DtipifAQHzvBSUG5697fM+7fXCV53d4Uaw==\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","NotBefore":"0001-01-01T00:00:00Z","NotAfter":"0001-01-01T00:00:00Z","CAName":""}
Error: POST failure of request: POST https://org1-ca:7054/enroll
{"hosts":["00e808471e05"],"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIIBSjCB8QIBADBlMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xp\nbmExFDASBgNVBAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMxFjAUBgNV\nBAMTDW9yZzEtYWRtaW4tY2EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASBr8+2\nnzdzj2MhJfTTgEsqt+p1AyKlXlrnq+Nd3MGX74mhpgeNEatlTfAxP5vCgMZ8o276\n1l9m8pD56NaXQqXeoCowKAYJKoZIhvcNAQkOMRswGTAXBgNVHREEEDAOggwwMGU4\nMDg0NzFlMDUwCgYIKoZIzj0EAwIDSAAwRQIhAIiWAai73sulrAcB4J1g/17VxekV\naW3/tCKQqCTiaYtEAiAoxUcleJ99DtipifAQHzvBSUG5697fM+7fXCV53d4Uaw==\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","NotBefore":"0001-01-01T00:00:00Z","NotAfter":"0001-01-01T00:00:00Z","CAName":""}: Post https://org1-ca:7054/enroll: dial tcp 172.19.0.2:7054: connect: connection refused

Do you see any thing to correct?

**Comment by seanbhart** [comment]
That might be a docker issue, but just to start, from inside the CLI service, do you get a successful connection with:
`curl -v org1-ca:7054`

**Comment by shobhitJava** [comment]
Take a look here: Getting error

[root@docker-repo orderer_solo]# docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS               NAMES
00e808471e05        hyperledger/fabric-ca-tools   "/bin/bash -c '/etc/…"   About an hour ago   Up About an hour                        org1-cli
67c16fa33b3f        hyperledger/fabric-ca         "/bin/bash -c '/etc/…"   3 hours ago         Up 3 hours          7054/tcp            org1-ca
[root@docker-repo orderer_solo]# docker exec -it 00e808471e05 bash
root@00e808471e05:/# curl -v org1-ca:7054
* Rebuilt URL to: org1-ca:7054/
*   Trying 172.19.0.2...
* connect to 172.19.0.2 port 7054 failed: Connection refused
* Failed to connect to org1-ca port 7054: Connection refused
* Closing connection 0
curl: (7) Failed to connect to org1-ca port 7054: Connection refused
root@00e808471e05:/#

**Comment by seanbhart** [comment]
Are those containers on the same network?  `docker network list` shows the full list, but you might need to check the docker-compose files to ensure those network names weren't changed.  Could possibly be a docker daemon issue

**Comment by shobhitJava** [comment]
It is on same network. I have deleted all other images and containers. What I think if the CAserver accessible inside the fabric cli. Is it not the cause of connection getting refused?

**Comment by seanbhart** [comment]
Yea, if you can't curl the CA service from the CLI, it'll fail with the `enroll` request as well.

Are you on Windows?  Do you know if you have your docker hosts set to default?

>`unix:///var/run/docker.sock` on Linux, and `tcp://127.0.0.1:2376` on Windows.

https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option

**Comment by shobhitJava** [comment]
I am on linux.

**Comment by shobhitJava** [comment]
As far as I know. It is default

**Comment by seanbhart** [comment]
I'm not a docker expert, but let's see what else might solve the issue.

Try setting `export CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=orderer_solo` inside the CLI

Change the network name if you modified that.

**Comment by shobhitJava** [comment]
sure. give me some time. I will get back to you

**Comment by shobhitJava** [comment]
hey, I have moved ahead of this issue. We can close it.

**Comment by seanbhart** [comment]
Good to hear.  Please let me know if it was an issue with the repo code.

**Comment by shobhitJava** [comment]
No. It was not due to code on repo
